apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-application
  namespace: arindam
  labels:
    app: gitops-application
    role: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-application
  template:
    metadata:
      labels:
        app: gitops-application
    spec:
      containers:
        - name: gitops-application
          image: arimlregistry.azurecr.io/arindam-app:4.0.0 # {"$imagepolicy": "flux:gitops-application"}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources: 
            limits:
              cpu: 700m
              memory: 1Gi
            request: 
              cpu: 500m
              memory: 500mi
          env: 
            - name: ENV_VAR_1
              value: "Value defined in deployment object"
