apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-application
  namespace: arindam
  labels:
    app: gitops-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-application
  template:
    metadata:
      labels:
        app: gitops-application
    spec:
      containers:
        - name: gitops-application
          image: >-
            arimlregistry.azurecr.io/arindam-app:3.0.0 # {"$imagepolicy": "flux:gitops-application"}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
