apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: gitops-application
  namespace: flux
spec:
  image: arimlregistry.azurecr.io/arindam-app
  interval: 1m0s
  provider: generic
  secretRef: 
    name: docker-config
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: gitops-application
  namespace: flux
spec:
  imageRepositoryRef:
    name: gitops-application
  policy:
    semver:
      range: '>=1.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata: 
  name: gitops-application
  namespace: flux
spec:
  git: 
    checkout: 
      ref: 
        branch: main
    commit: 
      author: 
        email: fluxbot@gitops.com
        name: flux-bot
      messageTemplate: | 
        This is an automated update from Flux 
        [ci skip]
    push: 
      branch: main
  interval: 1m
  sourceRef: 
    kind: GitRepository
    name: flux
  update: 
    path: ./gitops-application
    strategy: Setters
