apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- image-automation.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../gitops-application/deployment.yaml
patches:
  - path: patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: gitops-application
